cats_and_pets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pets.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PostView.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
    path('create/', views.PostCreateView.as_view(), name='create_post'),
]

pets/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    author = models.CharField(max_length=100)
    date = models.DateField()
    img = models.ImageField(upload_to='image/%Y')


    def get_absolute_url(self):
        return ('/')


    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Posts'
        verbose_name_plural = 'Posts'


class Comments(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=50)
    text_comments = models.TextField(max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Post', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Comments'
        verbose_name_plural = 'Comments'

pets/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'author', 'date', 'img']

pets/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post
from .form import CommentsForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View


class PostView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'pets/pets.html', {'post_list': posts})


class PostDetail(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'pets/pets_detail.html', {'post':post})


class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


class PostCreateView(generic.CreateView):
    model = Post
    fields = ['title', 'description', 'author', 'date', 'img']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}Cats and Pets{% endblock %}</title>
</head>


<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Cats and Pets</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/accounts/register">Registration</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="/accounts/login">Login</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="/create">Create post</a>
      </li>

    </ul>
      {% if user.is_authenticated %}
      <a class="nav-link" href="/">{{ user.username }}</a>
      {% else %}
      <a class="nav-link" href="/accounts/login">Please log in</a>
      {% endif %}

  </div>
</nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

templates/django_registration/registration_complete.html
{% extends 'base.html' %}
{% block content %}
<h2>Вы успешно зарегистрировались</h2>
{% endblock %}

templates/django_registration/registration_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/pets/create_post.html
{% extends 'base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/pets/pets.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">



		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>Лента</h3>
                    {% for post in post_list %}
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ post.img.url }}" width="150px"  /></a>
						</div>
						<div class="text left">
							<h4><a href="{{ post.id }}">{{post.title}}</a></h4>
							<p>{{post.description}}</p>
							<p>{{post.author}}</p>
							<p>{{post.date}}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
                    {% endfor %}

				</div>
			</div>

			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">cats and pets &copy;  Manovar </p>
	</div>
</div>
</body>
</html>
{% endblock %}

templates/pets/pets_detail.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">



		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{post.title}}</h3>
                  <p align="center">
                    <img src="{{ post.img.url }}" width="50%"/>
                  </p>
					<div class="item">

						<div class="text left">

							<p>{{post.description}}</p>
							<p>{{post.author}}</p>
							<p>{{post.date}}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>


				</div>
			</div>

			<div class="form-comment">
				<h3>"Оставить комментарий"</h3>
				<div>
					<form action="{% url 'add_comments' post.id %}" method="post">
						{% csrf_token %}

						<div>
							<label>Ваш комментарий</label>
							<textarea name= "text_comments"></textarea>
						</div>
						<div>
							<label>Ваше имя *</label>
							<input type="text" name="name">
						</div>
						<div>
							<label>Ваш email *</label>
							<input type="email" name="email">
						</div>
						<div>
							<input type="submit">
						</div>

					</form>
				</div>
			</div>

			<div>
				{% for comment in post.comments_set.all %}
				<div class="view-comment">
					<h4>{{ comment.name}}</h4>
				</div>
				<p>
					{{ comment.text_comments}}
				</p>
				{% endfor %}
			</div>

			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">cats and pets &copy;  Manovar </p>
	</div>
</div>

</body>
</html>
{% endblock %}

templates/pets/post_form.html
{% extends 'base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock %}